{% set name = "flytekitplugins-spark" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flytekitplugins-spark-{{ version }}.tar.gz
  sha256: da595af6dc15e6be7bfa9deb604643f0092f5f9d31935244edea8dd4bf6e0d55

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - flytekit >=1.0.0b3,<1.2.0
    - pyspark >=3.0.0

test:
  imports:
    - flytekitplugins.spark
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/flytekitplugins-spark/
  summary: Spark 3 plugin for flytekit
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  description: |
    Spark 3 plugin for Flytekit: `{{ name }}`

    PyPI: [https://pypi.org/project/flytekitplugins-spark/](https://pypi.org/project/flytekitplugins-spark/)

  doc_url: https://github.com/flyteorg/flytekit/tree/master/plugins
  dev_url: https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-spark

extra:
  recipe-maintainers:
    - sugatoray
